### ISSUE TITLE
set the admin of the group ?

### ISSUE THREAD

**Issue by ben-henoida** [AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin#20]
If I add "admin":"UserName" in create group as documented here https://www.applozic.com/docs/platform-api-chat.html#create-group

I receive the following error message:
`{errorCode: "AL-U-01", description: "user not found", displayMessage: "unable to process"}`

 How would you set the admin of the group ?

**Comment by Sunilkumarr** [comment]
first user need to be  register in applozic  then only you can set the admin  while creating a group
