### ISSUE TITLE
CFBundleIdentifier Collision

### ISSUE THREAD

**Issue by virtualprodigy** [AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin#22]
**Bugs**:  I am facing a CFBundleIdentifier Collision when I attempt to update my Ionic 2 iOS application to TestFlight. The specific error is 
**CFBundleIdentifier Collision - The Info.plist CFBundleIdentifier value 'com.applozic.framework' of 'myapp.app/Frameworks/Applozic.framework' is already in use by another application.**

## Expected Results
The application to uploads successfully to iTunesConnect

## Actual Results
The upload fails with the error **CFBundleIdentifier Collision - The Info.plist CFBundleIdentifier value 'com.applozic.framework' of 'myapp.app/Frameworks/Applozic.framework' is already in use by another application.**

## Steps to Reproduce
Achieve application in xCode and attempt to submit to iTunesConnect

Applozic Cordova SDK version: 
    
    Applozic Cordova plugin : id="com.applozic.phonegap" version="0.8.0"
 
Ionic Enviroment: 
    
    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    Node              : v6.10.3
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 

Android/iOS or both: iOS

Android/iOS device: N/A this is an upload to iTunesConnect issue

Android/iOS OS version: N/A this is an upload to iTunesConnect issue

Dependencies used with version: 

Not sure if it matters but I'm using the following : 
    PhoneGap push plugin version 1.8.1
    Cocoapods version 1.2.1

**Comment by adarshmishra** [comment]
@virtualprodigy please contact at support@applozic.com for framework required for iTunes upload.

**Comment by engr-erum** [comment]
Hi, how u resolved this issue ?
