### ISSUE TITLE
getConversationList crashes android app

### ISSUE THREAD

**Issue by sirpy** [AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin#25]
using latest master
running in chrome inspect view of the app:
applozic.getConversationList({clientGroupId:101278},x => console.log(x),y => console.log(y))

causes application to crash

**Comment by reytum** [comment]
@sirpy getConversationList(data) accepts an object which is defined by messageListModel below. You can try to call it like below:

getConversationList(){

  var messageListModel = {
  'startTime' : null, //start time
 'endTime' : null, //end time
 'contactId' : null, //pass contact id to get the message list for that contact
'searchString' : null, // pass the search string to get the latest messages that match the search string
'channelKey' : null, // pass the channel key to get the message list for that channel
'conversationId' : null,
'isScroll' : false, //is scroll will be false if you want to get all list of chats  
'isSkipRead' : false
  };

  applozic.getConversationList(messageListModel,(respone)=> {
  console.log("get Conversation list",respone);

  });

  }
