### ISSUE TITLE
Ionic Add Plugin Fails

### ISSUE THREAD

**Issue by virtualprodigy** [AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin#26]
Whenever I run the command ionic cordova plugin add https://github.com/AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin.git, the install fails with 
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin.git /var/root/.npm/_cacache/tmp/git-clone-a18e95bb
npm ERR! /private/var/root/.npm/_cacache/tmp/git-clone-a18e95bb/.git: Permission denied

**Comment by mukeshthawani** [comment]
Use sudo to run the command.
