### ISSUE TITLE
How to get Group chat List in Android.

### ISSUE THREAD

**Issue by bharatguptacgt** [AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin#27]
## Goals
want to fetch all group chats list in Android. Suppose if i have 10 groups then, i want to show all of them in a page. 

## Expected Results
all groups listed in a page like you are showing in your people activity 
for andorid app

**Comment by mukeshthawani** [comment]
Please file issue on the Android [repo](https://github.com/AppLozic/Applozic-Android-SDK)
