### ISSUE TITLE
Cannot create a group with clientGroupId

### ISSUE THREAD

**Issue by vegalp** [AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin#29]
We are already using web plugin, where groups are created with the optional parameter clientGroupId, and our work flow with groups is by clientGroupId.
 
In here when creating a group there is no option for setting the clientGroupId, is set by default to be same as groupId.

## Goals
I need to use clientGroupId that is provided by us, because our work flow is with clientGroupId .

## Expected Results
To have an option when create a new group to set the clientGroupId , as in web plugin.

**Comment by reytum** [comment]
Hello @vegalp ,

You can create a group as below:

  var group = {
         	'groupName': 'hey',
         	'groupMemberList': ['userid1', 'userid2', 'userid3'], // Pass list of user Ids in groupMemberList
         	'imageUrl': 'https://www.applozic.com/favicon.ico',
                'clientGroupId': 'your-client-group-id',
         	'type' : 1,    //'type' : 1, //(required) 1:private, 2:public, 5:broadcast,7:GroupofTwo
         	'metadata' : {
         		'key1' : 'value1',
         		'key2' : 'value2'
         	}
         };
  applozic.createGroup(group, function() {}, function() {});

**Comment by vegalp** [comment]
@reytum Already tried that. Group is successfully created but clientGroupID is same with groupID, when i check on dashboard.
Bellow is my code:
var group = {
	'groupName': $scope.campaign.title + ' ' + influencerObj.displayName,
	'groupMemberList': groupMembers, 
	'imageUrl': $scope.campaign.photo,
	'clientGroupId': groupID,
	'type' : 1
};
		  
chat.createGroup(group); 
..........

this.createGroup =  function(group){
	applozic.createGroup(group,function(response) {       
		console.log(JSON.stringify(response));
	}, function () {      
	});
}

**Comment by reytum** [comment]
Hello  @vegalp,
Updated the plugin, can you check again.

**Comment by vegalp** [comment]
Hi @reytum. It's working. Thx
