### ISSUE TITLE
onMessageReceived event

### ISSUE THREAD

**Issue by vegalp** [AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin#31]
In the web plugin there is an event onMessageReceived. Is such an event in cordova/ionic plugin or something similar that will catch the event when message is received?

**Comment by reytum** [comment]
@vegalp Our cordova/ionic plugin is a wrapper around the native SDK. The message received events will be in the native SDK and currenty are not accessible through the plugin. Let us know some more details on why you need the events and we may have an easy solution for that.

**Comment by vegalp** [comment]
@reytum We use this event onMessageReceived to update the number of unread message in out custom badge that we have put it on chat icon. Is there some other way how we can have unread message in real time, without using timer or interval in order to check the number of unread messages

**Comment by reytum** [comment]
@vegalp You can use the [broadcast plugin](https://www.npmjs.com/package/cordova-plugin-broadcaster)
For Android Listen for the Broadcast action : APPLOZIC_UNREAD_COUNT
For iOS Listen for the Notification action : NEW_MESSAGE_NOTIFICATION

Then you can call the getTotalUnreadCount() and every time you receive the action, just increment the count by one.
