### ISSUE TITLE
Is this plugin available for free only for 31 days?

### ISSUE THREAD

**Issue by pallaviMN** [AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin#32]
## Code Sample

Applozic Cordova SDK version: ?

Android/iOS or both: ?

Android/iOS device: ?

Android/iOS OS version: ?

Dependencies used with version: ?

**Comment by Sunilkumarr** [comment]
For Development and testing its free for 31 days after that, you need to subscribe to one of our plans from [pricing page](https://www.applozic.com/messaging-api-price.html)
