### ISSUE TITLE
applozic is not define on ionic 2

### ISSUE THREAD

**Issue by arsewizz** [AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin#7]
i'm working with ionic 2 and it tell me applozic is not define

**Comment by devashishmamgain** [comment]
@arsewizz looks like you are calling the applozic functions before the platform is ready.
Call it after the platform is ready. For example:

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Platform } from 'ionic-angular'; 

declare var applozic:any;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, platform: Platform) {
  	platform.ready().then(() => {
  		 var alUser = {
            'userId' : 'debug3',   //Replace it with the userId of the logged in user
            'password' : 'debug3',  //Put password here
            'authenticationTypeId' : 1,
            'applicationId' : 'applozic-sample-app'
        };

	   applozic.login(alUser, function() {
	        		applozic.launchChat(function() {}, function() {});
	        	}, function() {});
    });
  }

}
```

**Comment by arsewizz** [comment]
what about video and audio call ?

**Comment by afixibiranchi** [comment]
I am still getting the error on the iPhone and Android devices.

Here is my code below:
```

import { Component } from '@angular/core';
import { NavController, NavParams } from 'ionic-angular';
import { Platform } from 'ionic-angular';

declare var applozic: any;

@Component({
  selector: 'page-messages',
  templateUrl: 'messages.html',
})
export class Messages {

  constructor(public navCtrl: NavController, public navParams: NavParams,
    public platform: Platform) {


    this.platform.ready().then(() => {
      //alert("platform ready");
      var alUser = {
        'userId': 'TestUser1',   //Replace it with the userId of the logged in user
        'password': 'qwerty',  //Put password here
        'authenticationTypeId': 1,
        'applicationId': 'applozic-sample-app' //replace "applozic-sample-app" with Application Key from Applozic 
      };
      //alert("login to chat");


      applozic.login(alUser, function (e) {
        alert("Login : " + e);
        applozic.launchChat(function () { alert("Success"); }, function () { alert("Failure"); });
      }, function (err) { alert("Login Error: " + err); });

    }).catch((error) => {
      alert("Error in applogic : " + error);
    });

  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad Messages');
  }

}
```

**Comment by afixibiranchi** [comment]
I am still getting the error on iPhone and Android devices.

Here is my code below:

```
import { Component } from '@angular/core';
import { NavController, NavParams } from 'ionic-angular';
import { Platform } from 'ionic-angular';

declare var applozic: any;

@Component({
  selector: 'page-messages',
  templateUrl: 'messages.html',
})
export class Messages {

  constructor(public navCtrl: NavController, public navParams: NavParams,
    public platform: Platform) {


    this.platform.ready().then(() => {
      //alert("platform ready");
      var alUser = {
        'userId': 'TestUser1',   //Replace it with the userId of the logged in user
        'password': 'qwerty',  //Put password here
        'authenticationTypeId': 1,
        'applicationId': 'applozic-sample-app' //replace "applozic-sample-app" with Application Key from Applozic 
      };
      //alert("login to chat");


      applozic.login(alUser, function () {
        applozic.launchChat(function () { alert("Success"); }, function () { alert("Failure"); });
      }, function (err) { alert("Login Error: " + err); });

    }).catch((error) => {
      alert("Error in applogic : " + error);
    });

  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad Messages');
  }

}
```

**Comment by devashishmamgain** [comment]
Is the plugin added to the project?
Can you share a sample code which we can run and reproduce the issue?

**Comment by arsewizz** [comment]
Just publish a starter application if possible

**Comment by devashishmamgain** [comment]
uploaded sample code 
https://github.com/AppLozic/Applozic-Cordova-PhoneGap-Chat-Plugin/tree/master/samples/ionic2

See the following file for reference:
https://github.com/AppLozic/Applozic-Cordova-PhoneGap-Chat-Plugin/blob/master/samples/ionic2/src/pages/home/home.ts

userId, accessToken and applicationId needs to be replaced dynamically.

Also, please note that it will not work on web browser.

**Comment by arsewizz** [comment]
If i want to let my user to create a new account ? Or to reset password

Le 22 juin 2017 10:21, "Devashish Datt Mamgain" <notifications@github.com>
a écrit :

uploaded sample code
https://github.com/AppLozic/Applozic-Cordova-PhoneGap-
Chat-Plugin/tree/master/samples/ionic2

See the following file for reference:
https://github.com/AppLozic/Applozic-Cordova-PhoneGap-
Chat-Plugin/blob/master/samples/ionic2/src/pages/home/home.ts

userId, accessToken and applicationId needs to be replaced dynamically.

Also, please note that it will not work on web browser.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AppLozic/Applozic-Cordova-PhoneGap-Chat-Plugin/issues/7#issuecomment-310325726>,
or mute the thread

**Comment by devashishmamgain** [comment]
account creation and login is upto your application to implement, once user is logged in to your system, pass the information to Applozic plugin.

**Comment by arsewizz** [comment]
What about to make a Starter guide?

**Comment by devashishmamgain** [comment]
Let me know if you have anything specific in mind which is not present in ReadMe
https://github.com/AppLozic/Applozic-Cordova-PhoneGap-Chat-Plugin/blob/master/README.md

**Comment by kzsense** [comment]
Hi @devashishmamgain , I am getting the same error and I am using Ionic 3.
`Error: Uncaught (in promise): ReferenceError: applozic is not defined`
here is the code:
`import { Component } from '@angular/core';
import {IonicPage, NavController, NavParams, Platform} from 'ionic-angular';

import { RoomPage } from '../room/room';

declare let applozic: any;

@IonicPage()
@Component({
  selector: 'page-signin',
  templateUrl: 'signin.html',
})
export class SigninPage {

  constructor(public navCtrl: NavController, public navParams: NavParams, platform: Platform) {
      platform.ready().then(() => {
        let alUser = {
          'userId' : 'qop123',   //Replace it with the userId of the logged in user
          'password' : 'qop123',  //Put password here
          'authenticationTypeId' : 1,
          'applicationId' : '(my application id)'
        };

        applozic.login(alUser, function() {
          applozic.launchChat(function() {}, function() {});
        }, function() {});
      });
  }`

I followed this guild: https://github.com/AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin/blob/master/README.md
and install the plugin:
ionic cordova plugin add https://github.com/AppLozic/Applozic-Cordova-Ionic-PhoneGap-Chat-Plugin.git

I guess I should insert the script tag in the header, but the instruction didn't mention.
I tried `import * as applozic from '?(couldn't find the right folder)'` not work
